language: java
sudo: false
install: true
jdk:
- oraclejdk8
dist: trusty
before_install:
- chmod +x gradlew
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"
before_deploy: "./gradlew prepareUpload"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 'build/libs/mfsjeaMC.jar'
  skip_cleanup: true
  on:
    repo: RanolP/mfsjeaMC
    tags: true
