name: mfsjeaMC
version: @version@
main: io.github.ranolp.mfsjeamc.MfsjeaMC
author: Ranol_
description: mfsjea.jvm for Spigot
commands:
  enko:
    aliases: [영한, mfsjea, dudgks]
    description: "영타 → 한타 변환을 끄거나 켭니다, 혹은 메시지를 변환합니다."
  keyboard:
    aliases: [키보드]
    description: "입력/출력 키보드를 고정합니다."
  reloadconfig:
    description: "설정 파일을 새로 불러옵니다."
    permission: OP
    permission-message: "§c[!] §f관리자만 사용 가능한 명령어입니다."
